export const FETCH_BEERS_REQUEST = 'FETCH_BEERS_REQUEST'
export const FETCH_BEERS_SUCCES =  'FETCH_BEERS_SUCCES'
export const FETCH_BEERS_FAILURE = 'FETCH_BEERS_FAILURE'
export const FILTER_BEERS = 'FILTER_BEERS'